# Generated by Django 4.2 on 2023-05-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='data',
            field=models.JSONField(default=''),
        ),
    ]
